import { useLocation, useNavigate } from "react-router-dom";
import {
  Box,
  Button,
  Card,
  CardContent,
  Divider,
  Typography,
} from "@mui/material";

const Ticket = () => {
  const location = useLocation();
  const navigate = useNavigate();

  // Ticket generated by the backend.
  const ticket = location.state?.ticket;

  // If ticket data is missing.
  if (!ticket) {
    return (
      <Box>
        <Typography variant="h5">
          Ticket information not found.
        </Typography>

        <Button
          variant="contained"
          sx={{ mt: 2 }}
          onClick={() => navigate("/customer/trips")}
        >
          Back to Trips
        </Button>
      </Box>
    );
  }

  return (
    <Box sx={{ maxWidth: 700 }}>
      <Typography variant="h4" gutterBottom>
        Booking Confirmation
      </Typography>

      <Card>
        <CardContent>
          <Typography
            variant="h5"
            align="center"
            gutterBottom
          >
            Ticket Confirmed
          </Typography>

          <Typography
            align="center"
            color="success.main"
            sx={{ mb: 3 }}
          >
            {ticket.ticketStatus}
          </Typography>

          <Divider />

          <Box sx={{ mt: 3 }}>
            <Typography>
              <strong>Ticket Number:</strong>{" "}
              {ticket.ticketNumber}
            </Typography>

            <Typography sx={{ mt: 1 }}>
              <strong>Customer:</strong>{" "}
              {ticket.customerName}
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6">
            Journey Details
          </Typography>

          <Typography sx={{ mt: 2 }}>
            <strong>From:</strong>{" "}
            {ticket.sourceCity}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>To:</strong>{" "}
            {ticket.destinationCity}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>Bus:</strong>{" "}
            {ticket.busName}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>Bus Number:</strong>{" "}
            {ticket.busNumber}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>Seat(s):</strong>{" "}
            {ticket.seatNumbers?.join(", ")}
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6">
            Travel Details
          </Typography>

          <Typography sx={{ mt: 2 }}>
            <strong>Travel Date:</strong>{" "}
            {new Date(ticket.travelDate).toLocaleDateString()}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>Departure:</strong>{" "}
            {new Date(ticket.departureTime).toLocaleString()}
          </Typography>

          <Typography sx={{ mt: 1 }}>
            <strong>Arrival:</strong>{" "}
            {new Date(ticket.arrivalTime).toLocaleString()}
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6">
            Payment
          </Typography>

          <Typography
            variant="h5"
            sx={{ mt: 1 }}
          >
            ₹{ticket.amount}
          </Typography>

          <Button
            variant="contained"
            sx={{ mt: 4 }}
            onClick={() => navigate("/customer")}
          >
            Go to Dashboard
          </Button>
        </CardContent>
      </Card>
    </Box>
  );
};

export default Ticket;